"""Headless Chromium loop that keeps the YouTube cookies fresh.

Strategy (the "C" plan we discussed):

1. **Logged-in keep-alive (primary).** If the host's
   ``secrets/cookies.txt`` (or a previously saved Playwright storage state)
   contains a real signed-in session, we boot Chromium with that state,
   visit YouTube, confirm we're still authenticated, and play a short
   video to extend the session. Refreshed cookies are then exported.

2. **Anonymous fallback.** If step 1 detects we're no longer logged in
   (Google forced re-auth, the cookies expired, etc.), we still visit
   YouTube anonymously, accept the EU consent dialog if it appears, and
   play a video so we at least come away with the consent + visitor
   cookies. This covers a chunk of "Sign in to confirm you're not a
   bot" cases on its own and also tells the user (via logs) that they
   need to re-upload real cookies.

After every successful run we write the cookies to **two** places so
both layers of the app pick them up:

* ``secrets/cookies.txt`` (Netscape format) — same path the backend
  resolves via ``YT_DLP_COOKIES_PATH``, persisted across container
  restarts.
* The Valkey runtime override key ``ytdl:cookies:override`` (with
  TTL = ``COOKIES_OVERRIDE_TTL_SECONDS``, default 7d) — same key the
  backend's ``cookies.py`` service reads, so refreshed cookies take
  effect on the very next download without needing a restart.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import redis
from playwright.async_api import (
    Browser,
    BrowserContext,
    Error as PlaywrightError,
    TimeoutError as PlaywrightTimeout,
    async_playwright,
)


LOG_FORMAT = "%(asctime)s [%(levelname)s] %(message)s"
logging.basicConfig(level=os.environ.get("LOG_LEVEL", "INFO"), format=LOG_FORMAT)
log = logging.getLogger("cookie-refresh")


STATE_DIR = Path(os.environ.get("STATE_DIR", "/state"))
COOKIES_FILE = Path(os.environ.get("COOKIES_FILE", "/run/cookies.txt"))
TEST_VIDEO_URL = os.environ.get(
    "COOKIE_REFRESH_TEST_VIDEO_URL",
    # First video ever uploaded to YouTube. Short, public, never going away.
    "https://www.youtube.com/watch?v=jNQXAC9IVRw",
)
REDIS_URL = os.environ.get("REDIS_URL", "redis://valkey:6379/0")
REDIS_KEY = "ytdl:cookies:override"
OVERRIDE_TTL = int(
    os.environ.get("COOKIES_OVERRIDE_TTL_SECONDS", str(7 * 24 * 60 * 60))
)
INTERVAL_SECONDS = int(
    os.environ.get("COOKIE_REFRESH_INTERVAL_SECONDS", str(6 * 60 * 60))
)
USER_AGENT = os.environ.get(
    "COOKIE_REFRESH_USER_AGENT",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
)


# ---------------------------------------------------------------------------
# Netscape cookies.txt <-> Playwright cookie list
# ---------------------------------------------------------------------------


def parse_netscape(text: str) -> list[dict[str, Any]]:
    """Convert a yt-dlp / browser-extension cookies.txt into Playwright's shape."""
    out: list[dict[str, Any]] = []
    for line in text.splitlines():
        stripped = line.strip()
        # Files exported by some browser extensions use ``#HttpOnly_`` as a
        # prefix on http-only cookies — keep them, just strip the prefix.
        if stripped.startswith("#HttpOnly_"):
            stripped = stripped[len("#HttpOnly_") :]
        elif not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split("\t")
        if len(parts) != 7:
            continue
        domain, _include_sub, path, secure, expires, name, value = parts
        try:
            expires_f = float(expires)
        except ValueError:
            expires_f = -1
        out.append(
            {
                "name": name,
                "value": value,
                "domain": domain,
                "path": path or "/",
                "expires": expires_f if expires_f > 0 else -1,
                "httpOnly": False,
                "secure": secure.upper() == "TRUE",
                "sameSite": "Lax",
            }
        )
    return out


def to_netscape(cookies: list[dict[str, Any]]) -> str:
    """Render Playwright cookies back into the Netscape format yt-dlp expects."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by yt-downloader cookie-refresh service.",
        "",
    ]
    for c in cookies:
        domain = c["domain"]
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = c.get("expires") or 0
        # Playwright uses -1 for session cookies; yt-dlp wants 0.
        if expires <= 0:
            expires_int = 0
        else:
            expires_int = int(expires)
        name = c["name"]
        value = c["value"]
        # cookies.txt is tab-separated; values containing tabs are rare but
        # yt-dlp will reject the whole file if any line has the wrong column
        # count, so be defensive.
        if "\t" in value or "\t" in name:
            log.warning("skipping cookie %s: contains tab in name/value", name)
            continue
        lines.append(
            f"{domain}\t{include_sub}\t{path}\t{secure}\t{expires_int}\t{name}\t{value}"
        )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# State bootstrap
# ---------------------------------------------------------------------------


def ensure_state_dir() -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)


def load_initial_state() -> dict[str, Any] | str | None:
    """Return what to feed into ``new_context(storage_state=...)``.

    * Path string → existing Playwright storage_state.json file.
    * Dict → freshly-built storage state from cookies.txt (first run).
    * None → no state, run anonymous-only.
    """
    state_path = STATE_DIR / "storage_state.json"
    if state_path.exists() and state_path.stat().st_size > 0:
        log.info("Reusing storage_state at %s", state_path)
        return str(state_path)

    if COOKIES_FILE.exists() and COOKIES_FILE.stat().st_size > 0:
        text = COOKIES_FILE.read_text(encoding="utf-8", errors="replace")
        cookies = parse_netscape(text)
        if cookies:
            log.info(
                "Bootstrapping storage_state from %s (%d cookies)",
                COOKIES_FILE,
                len(cookies),
            )
            return {"cookies": cookies, "origins": []}
        log.warning("%s has no parseable cookies — running anonymous-only", COOKIES_FILE)

    log.info("No saved state and no cookies.txt — running anonymous-only")
    return None


# ---------------------------------------------------------------------------
# Refresh loop
# ---------------------------------------------------------------------------


async def _detect_signed_in(page) -> bool:
    """Best-effort check: is YouTube treating us as a logged-in account?"""
    try:
        return bool(
            await page.evaluate(
                """() => {
                    const avatar = document.querySelector(
                        'button#avatar-btn, ytd-topbar-menu-button-renderer img'
                    );
                    return Boolean(avatar);
                }"""
            )
        )
    except PlaywrightError:
        return False


async def _accept_consent(page) -> None:
    """Click the EU consent "Accept all" button if it appears."""
    try:
        consent = page.locator(
            'button:has-text("Accept all"), '
            'button[aria-label*="Accept the use of cookies"]'
        ).first
        if await consent.count():
            await consent.click(timeout=3000)
            # Don't wait for networkidle here — YouTube keeps issuing
            # background requests indefinitely, especially on flagged IPs,
            # and we'd hang the whole refresh on a step that's already
            # functionally done.
            await asyncio.sleep(2)
            log.info("Consent dialog accepted")
    except (PlaywrightTimeout, PlaywrightError) as exc:
        log.warning("consent handling skipped: %s", exc)


async def _play_test_video(page) -> None:
    try:
        await page.goto(
            TEST_VIDEO_URL, wait_until="domcontentloaded", timeout=20000
        )
        try:
            await page.wait_for_selector("video", timeout=10000)
            # Fire .play() inside the page but DO NOT await its promise —
            # on a flagged datacenter IP YouTube can serve an "unavailable"
            # player whose play() promise never resolves, hanging the
            # whole refresh forever. We just kick off playback and move on.
            await page.evaluate(
                "() => { const v = document.querySelector('video'); "
                "if (v && v.play) { v.play().catch(() => {}); } return null; }"
            )
        except (PlaywrightTimeout, PlaywrightError) as exc:
            log.debug("video element not playable: %s", exc)
        # Short pause so the session cookies (YSC, VISITOR_INFO1_LIVE_PRIVATE
        # etc.) have time to land.
        await asyncio.sleep(3)
    except (PlaywrightTimeout, PlaywrightError) as exc:
        log.warning("test video step failed: %s", exc)


def _push_to_redis(content: str) -> None:
    try:
        r = redis.from_url(REDIS_URL, socket_connect_timeout=5)
        r.set(REDIS_KEY, content, ex=OVERRIDE_TTL)
    except Exception as exc:  # noqa: BLE001 — Redis can fail in a few ways
        log.warning("Redis write failed: %s (file is still up to date)", exc)
        return
    log.info("Pushed %d bytes to Valkey override (TTL %ds)", len(content), OVERRIDE_TTL)


def _log_session_health(cookies: list[dict[str, Any]]) -> None:
    sid = next((c for c in cookies if c["name"] == "__Secure-1PSID"), None)
    if not sid:
        log.warning(
            "__Secure-1PSID not present — anonymous session. yt-dlp may still "
            "hit the bot challenge on flagged IPs. Re-upload secrets/cookies.txt "
            "from a logged-in browser to restore the keep-alive."
        )
        return
    exp = sid.get("expires") or 0
    if exp <= 0:
        log.info("__Secure-1PSID present (session cookie, no expiry)")
        return
    when = datetime.fromtimestamp(exp, tz=timezone.utc).isoformat()
    days = (exp - time.time()) / 86400
    log.info("__Secure-1PSID expires at %s (~%.1f days)", when, days)


async def run_once() -> None:
    ensure_state_dir()
    initial_state = load_initial_state()
    # Hard ceiling on the entire pass: if Playwright / YouTube hangs on
    # any step (a captcha redirect, a stalled network request, a never-
    # resolving play() promise), we bail out cleanly so the next cycle
    # gets to try again instead of the whole loop wedging forever.
    try:
        await asyncio.wait_for(_run_once_inner(initial_state), timeout=150)
    except asyncio.TimeoutError:
        log.error(
            "refresh exceeded the 150s ceiling and was aborted; will retry next cycle"
        )


async def _run_once_inner(initial_state: dict[str, Any] | str | None) -> None:
    async with async_playwright() as p:
        browser: Browser = await p.chromium.launch(
            headless=True,
            args=[
                # Tell sites we're not Selenium so YouTube doesn't refuse to
                # serve the player.
                "--disable-blink-features=AutomationControlled",
                # Container memory is tight; one process is enough.
                "--disable-dev-shm-usage",
            ],
        )

        ctx_kwargs: dict[str, Any] = {
            "user_agent": USER_AGENT,
            "locale": "en-US",
            "viewport": {"width": 1280, "height": 720},
        }
        if initial_state is not None:
            ctx_kwargs["storage_state"] = initial_state

        context: BrowserContext = await browser.new_context(**ctx_kwargs)
        try:
            page = await context.new_page()

            log.info("Visiting YouTube to verify session state")
            await page.goto(
                "https://www.youtube.com/feed/subscriptions",
                wait_until="domcontentloaded",
                timeout=30000,
            )
            try:
                await page.wait_for_load_state("networkidle", timeout=10000)
            except PlaywrightTimeout:
                # Subscriptions page often keeps streaming; that's fine.
                pass

            signed_in = await _detect_signed_in(page)
            if signed_in:
                log.info("Detected signed-in YouTube session — keep-alive path")
            else:
                log.info(
                    "No signed-in session detected — anonymous fallback "
                    "(re-upload secrets/cookies.txt from a logged-in browser "
                    "if you want the keep-alive path)"
                )
                await page.goto(
                    "https://www.youtube.com/",
                    wait_until="domcontentloaded",
                    timeout=30000,
                )
                await _accept_consent(page)

            await _play_test_video(page)

            cookies = await context.cookies(
                [
                    "https://www.youtube.com/",
                    "https://youtube.com/",
                    "https://www.google.com/",
                    "https://accounts.google.com/",
                ]
            )
            # Persist state for next run before we close the context.
            await context.storage_state(path=str(STATE_DIR / "storage_state.json"))

            relevant = [
                c
                for c in cookies
                if any(
                    d in c["domain"]
                    for d in ("youtube.com", "google.com", "ytimg.com")
                )
            ]
            if not relevant:
                log.error("No usable cookies extracted; skipping write")
                return

            netscape = to_netscape(relevant)
            try:
                COOKIES_FILE.write_text(netscape, encoding="utf-8")
                log.info(
                    "Wrote %d cookies to %s", len(relevant), COOKIES_FILE
                )
            except OSError as exc:
                log.error("failed to write %s: %s", COOKIES_FILE, exc)

            _push_to_redis(netscape)
            _log_session_health(relevant)
        finally:
            await context.close()
            await browser.close()


async def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--once",
        action="store_true",
        help="Run a single refresh pass and exit (useful for ad-hoc / cron / debugging).",
    )
    args = parser.parse_args(argv)

    if args.once:
        try:
            await run_once()
        except Exception:
            log.exception("refresh failed")
            return 1
        return 0

    log.info(
        "cookie-refresh starting: interval=%ds, test_video=%s, ttl=%ds",
        INTERVAL_SECONDS,
        TEST_VIDEO_URL,
        OVERRIDE_TTL,
    )
    while True:
        try:
            await run_once()
            log.info("Refresh complete; sleeping %ds", INTERVAL_SECONDS)
            await asyncio.sleep(INTERVAL_SECONDS)
        except Exception:
            # Don't crashloop — log and back off briefly so transient YouTube
            # blips (5xx, captcha pages) don't burn through Docker's restart
            # backoff and end up unnoticed in `restart: always`.
            log.exception("refresh failed; backing off 5min")
            await asyncio.sleep(300)


if __name__ == "__main__":
    sys.exit(asyncio.run(main(sys.argv[1:])))
