"use client";

import { useEffect, useRef, useState } from "react";
import { KeyRound, Loader2, X } from "lucide-react";
import { api, ApiError } from "@/lib/api";

const STORAGE_DISMISS_REASON = "ytdl_cookies_modal_last_reason";

export type OpenReason =
  | { kind: "metadata"; message: string; url: string }
  | { kind: "job"; message: string; jobId: string }
  | { kind: "manual" };

export function CookiesModal({
  open,
  reason,
  onClose,
  onSaved,
}: {
  open: boolean;
  reason: OpenReason | null;
  onClose: () => void;
  onSaved: (reason: OpenReason | null) => void;
}) {
  const [content, setContent] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  useEffect(() => {
    if (open) {
      // Don't preserve old content across separate openings; stale cookies are
      // the entire reason the modal is showing.
      setContent("");
      setError(null);
      // Focus the textarea so the user can paste immediately.
      setTimeout(() => textareaRef.current?.focus(), 50);
      // Remember why it opened so we don't spam the user on every poll tick.
      if (reason) {
        try {
          window.localStorage.setItem(STORAGE_DISMISS_REASON, JSON.stringify(reason));
        } catch {
          /* noop */
        }
      }
    }
  }, [open, reason]);

  if (!open) return null;

  const submit = async () => {
    if (!content.trim()) {
      setError("Paste the cookies.txt content first.");
      return;
    }
    setSaving(true);
    setError(null);
    try {
      await api.saveCookies(content);
      onSaved(reason);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to save cookies");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="card w-full max-w-2xl space-y-4 p-5">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-center gap-2">
            <KeyRound className="h-5 w-5 text-amber-500" />
            <h2 className="text-lg font-semibold">YouTube cookies required</h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-md p-1 text-muted-foreground hover:bg-muted"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {reason && reason.kind !== "manual" && (
          <p className="rounded-md bg-amber-50 px-3 py-2 text-sm text-amber-800">
            {reason.message}
          </p>
        )}

        <div className="space-y-2 text-sm text-muted-foreground">
          <p>
            Export a fresh <code>cookies.txt</code> from a logged-in YouTube browser tab
            (Netscape format), then paste the whole file below. Cookies are stored in
            the server and used for the next <i>~7 days</i> of downloads.
          </p>
          <details className="text-xs">
            <summary className="cursor-pointer font-medium text-foreground hover:underline">
              How to export cookies
            </summary>
            <ol className="mt-2 list-decimal space-y-1 pl-5">
              <li>
                Install{" "}
                <a
                  className="text-primary underline"
                  href="https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc"
                  target="_blank"
                  rel="noreferrer"
                >
                  Get cookies.txt LOCALLY
                </a>{" "}
                (Chrome) or{" "}
                <a
                  className="text-primary underline"
                  href="https://addons.mozilla.org/firefox/addon/cookies-txt/"
                  target="_blank"
                  rel="noreferrer"
                >
                  cookies.txt
                </a>{" "}
                (Firefox).
              </li>
              <li>Open an incognito window and sign into YouTube.</li>
              <li>Open any video for 5 seconds (seeds the session cookies).</li>
              <li>Click the extension → Export → open the downloaded file.</li>
              <li>Copy the entire contents and paste here.</li>
            </ol>
          </details>
        </div>

        <textarea
          ref={textareaRef}
          className="input min-h-[200px] w-full font-mono text-xs"
          placeholder="# Netscape HTTP Cookie File&#10;# This file is generated by yt-dlp.  Do not edit.&#10;..."
          value={content}
          onChange={(e) => setContent(e.target.value)}
          spellCheck={false}
        />

        {error && (
          <div className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>
        )}

        <div className="flex items-center justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            className="rounded-md border border-border px-3 py-2 text-sm hover:bg-muted"
            disabled={saving}
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={submit}
            disabled={saving || !content.trim()}
            className="btn-primary"
          >
            {saving && <Loader2 className="h-4 w-4 animate-spin" />}
            Save cookies
          </button>
        </div>
      </div>
    </div>
  );
}
